### ISSUE TITLE
exported methods from modules don't survive between code cells

### ISSUE THREAD

**Issue by demianriccardi** [zmughal/p5-Devel-IPerl#23]
use Modern::Perl;
say 'something'; #works

new cell
say 'something'; #error

**Comment by zmughal** [comment]
Ah, there was another plugin that Reply needs to load: Hints. This should fix it.

**Comment by zmughal** [comment]
@demianriccardi, did this fix work for you?

**Comment by demianriccardi** [comment]
Yes!!  Thanks, @zmughal!
