### ISSUE TITLE
Colors in the notebook?

### ISSUE THREAD

**Issue by demianriccardi** [zmughal/p5-Devel-IPerl#24]
Is there a way to get some variable and function colors into the notebook?

**Comment by zmughal** [comment]
Is something like the following not working?

![selection_284](https://cloud.githubusercontent.com/assets/94489/5996960/aaef6578-aa79-11e4-9c00-b01fe2a05157.png)

That's on a local notebook, but I'm not sure how to get Perl syntax highlighting on nbviewer working properly ([see example](http://nbviewer.ipython.org/gist/zmughal/d8a37222c814956aebb8)):

![selection_285](https://cloud.githubusercontent.com/assets/94489/5997005/9648e062-aa7a-11e4-8d93-544230b69b4a.png)

**Comment by zmughal** [comment]
I found out why the nbviewer isn't highlighting Perl properly. The nbconvert tool for IPython uses [pyments](http://pygments.org/) in the background and their lexer doesn't handle Perl completely. Time to fix it. :-P

**Comment by demianriccardi** [comment]
I don't get those nice colors in my local notebook. I may be missing a lib or something.  I'll see if switching browsers helps.

**Comment by demianriccardi** [comment]
I'm not sure what I did exactly, but the colors are working now.
