### ISSUE TITLE
TOP=`readlink -f "$TOP"`

### ISSUE THREAD

**Issue by demianriccardi** [zmughal/p5-Devel-IPerl#30]
The readlink line in the iperl script is causing the kernel to crash on my os x machine.  I commented out the line and it works well for me.

**Comment by demianriccardi** [comment]
>homebrew install coreutils 

gives greadlink, which works.

**Comment by zmughal** [comment]
That's a good enough reason for me to start moving from the shell script to Perl. Especially since Windows doesn't have bash.
