### ISSUE TITLE
 stty: stdin isn't a terminal

### ISSUE THREAD

**Issue by demianriccardi** [zmughal/p5-Devel-IPerl#31]
using the command line from a cell with back ticks worked for me before (e.g. `perldoc Foo::Bar`), but not with the most recent changes.

**Comment by zmughal** [comment]
Oh, this is a particular issue with using a backtick on `perldoc`. `perldoc` tries to detect if it is on a terminal or not.

Try:
```perl
print `perldoc Try::Tiny 2>/dev/null`;
```

**Comment by zmughal** [comment]
You can make a helper function for that too!

```perl
IPerl->helper( get_perldoc => sub {
	shift;
	print `perldoc @_ 2>/dev/null`;
	return; # so that the final return value is not printed
})

**Comment by zmughal** [comment]
Or, if you want to get fancy:

```
IPerl->helper( get_perldoc => sub {
	shift;
	my $html =  `perldoc -ohtml @_ 2>/dev/null`;
	return IPerl->html( $html );
});

# ...
IPerl->get_perldoc('Try::Tiny');
```

**Comment by zmughal** [comment]
Here's what it looks like: <http://nbviewer.ipython.org/github/zmughal/zmughal-iperl-notebooks/blob/master/IPerl-demos/20150211_An_IPerl_helper_for_perldoc_HTML.ipynb>.

**Comment by demianriccardi** [comment]
WOW!
